project_four/app_four/urls.py
from django.urls import re_path
from app_four import views


app_name = 'app_four'

urlpatterns = [
    re_path(r'^relative/$', views.relative, name='relative'),
    re_path(r'^other/$', views.other, name='other'),
    
    
]

project_four/project_four/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path
from app_four import views

urlpatterns = [

    re_path(r'^$', views.index, name='index'),
    path('admin/', admin.site.urls),
    re_path(r'^app_four/', include('app_four.urls')),
    
]

project_four/app_four/models.py
from django.db import models

# Create your models here.

project_four/app_four/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict = {'text':'hello world', 'number': 100 } 
    return render(request, 'app_four/index.html', context_dict)

def other(request):
    return render(request, 'app_four/other.html')

def relative(request):
    return render(request, 'app_four/relative_url_template.html')

project_four/templates/app_four/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class ="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
                <li><a class ="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="navbar-link" href="{% url 'app_four:other' %}">Other</a></li>
            </ul>

        </div>

    </nav>

    <div class="container">

        {% block body_block %}
        {% comment %} Anything outside of this will be inherited if you extend {% endcomment %}
        {% endblock body_block %}

    </div>
    
</body>
</html>

project_four/templates/app_four/index.html
<!DOCTYPE html>
{% extends 'app_four/base.html' %}
{% load my_extras %}

{% block body_block %}
    <h1>Welcom to Index</h1>
    <h2>Template inheritance</h2>
    <h1>
        {{ text|cutter_filter:' ' }}
    </h1>
    <h1>
        {{ number|add:"99"}}
    </h1>
  
   
{% endblock body_block %}
    

project_four/templates/app_four/other.html
<!DOCTYPE html>
{% extends "app_four/base.html" %}

    {% block body_block %}
        <h1>Welcome to other</h1>
        <h2>Template Inheritance</h2>
    {% endblock body_block %}
    

project_four/templates/app_four/relative_url_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome to relative url templates</h1>
    <a href="{% url 'app_four:other' %}">THE OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">ADMIN</a>
    <a href="{% url 'index' %}">INDEX</a>
</body>
</html>